export const INIT_GET_DATA_ALL_PODCAST = 'INIT_GET_DATA_ALL_PODCAST';
export const GET_ALL_PODCAST_DATA = 'GET_ALL_PODCAST_DATA';
export const GET_ALL_PODCAST_DATA_SUCCESS = 'GET_ALL_PODCAST_DATA_SUCCESS';
export const GET_ALL_PODCAST_DATA_ERROR = 'GET_ALL_DATA_ERROR';

export const INIT_GET_PODCAST_DETAILS = 'INIT_GET_PODCAST_DETAILS';
export const GET_PODCAST_DETAILS = 'GET_PODCAST_DETAILS';
export const GET_PODCAST_DETAILS_SUCCESS = 'GET_PODCAST_DETAILS_SUCCESS';
export const GET_PODCAST_DETAILS_ERROR = 'GET_PODCAST_DETAILS_ERROR';

export const INIT_GET_PODCAST_EPISODES = 'INIT_GET_PODCAST_EPISODES';
export const GET_PODCAST_EPISODES = 'GET_PODCAST_EPISODES';
export const GET_PODCAST_EPISODES_SUCCESS = 'GET_PODCAST_EPISODES_SUCCESS';
export const GET_PODCAST_EPISODES_ERROR = 'GET_PODCAST_EPISODES_ERROR';


export const INIT_GET_EPISODE_DETAILS = 'INIT_GET_EPISODE_DETAILS';
export const GET_EPISODE_DETAILS = 'GET_EPISODE_DETAILS';
export const GET_EPISODE_DETAILS_SUCCESS = 'GET_EPISODE_DETAILS_SUCCESS';
export const GET_EPISODE_DETAILS_ERROR = 'GET_EPISODE_DETAILS_ERROR';
