export const INIT_GET_DATA_ALL_PODCAST = 'INIT_GET_DATA_ALL_PODCAST';
export const GET_ALL_PODCAST_DATA = 'GET_ALL_PODCAST_DATA';
export const GET_ALL_PODCAST_DATA_SUCCESS = 'GET_ALL_PODCAST_DATA_SUCCESS';
export const GET_ALL_PODCAST_DATA_ERROR = 'GET_ALL_DATA_ERROR';
